### ISSUE TITLE
Map loop for testing adv block

### ISSUE THREAD

**Issue by v-nhandt21** [a10036gt/EV3-AdvMotorControllers-Block#2]
I am a student in University of science, I found your demo on youtube so perfect, can you share your pdf file of the map you are using for testing these blocks

Thank you

**Comment by a10036gt** [comment]
Leave your email here, I will sent you the PDF file.

**Comment by v-nhandt21** [comment]
> Leave your email here, I will sent you the PDF file.

Thank you very much for your reply, my email is:
dtnhan@apcs.vn
